import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';
import * as Material from '@angular/material';
import {DragDropModule} from '@angular/cdk/drag-drop';
import {ScrollingModule} from '@angular/cdk/scrolling';
import {CdkTableModule} from '@angular/cdk/table';
import {CdkTreeModule} from '@angular/cdk/tree';
import {A11yModule} from '@angular/cdk/a11y';
@NgModule({
  declarations: [],
  imports: [
    CommonModule,
    Material.MatToolbarModule,
    Material.MatTableModule,
    Material.MatPaginatorModule,
    Material.MatSortModule,
    Material.MatFormFieldModule,
    Material.MatGridListModule,
    Material.MatTableModule,
    Material.MatAutocompleteModule,
    Material.MatBottomSheetModule,
    Material.MatBadgeModule,
    Material.MatButtonModule,
    Material.MatButtonToggleModule,
    Material.MatCardModule,
    Material.MatCheckboxModule,
    Material.MatChipsModule,
    Material.MatDatepickerModule,
    Material.MatDialogModule,
    Material.MatDividerModule,
    Material.MatExpansionModule,
    Material.MatGridListModule,
    Material.MatIconModule,
    Material.MatInputModule,
    Material.MatListModule,
    Material.MatMenuModule,
    Material.MatNativeDateModule,
    Material.MatPaginatorModule,
    Material.MatProgressBarModule,
    Material.MatProgressSpinnerModule,
    Material.MatRadioModule,
    Material.MatRippleModule,
    Material.MatSelectModule,
    Material.MatSidenavModule,
    Material.MatSliderModule,
    Material.MatSlideToggleModule,
    Material.MatSnackBarModule,
    Material.MatSortModule,
    Material.MatStepperModule,
    Material.MatTableModule,
    Material.MatTabsModule,
    Material.MatToolbarModule,
    Material.MatTooltipModule,
    Material.MatTreeModule,
    Material.MatFormFieldModule,
    Material.MatInputModule
  ],
  exports: [
    Material.MatToolbarModule,
    Material.MatTableModule,
    Material.MatPaginatorModule,
    Material.MatSortModule,
    Material.MatFormFieldModule,
    Material.MatGridListModule,
    Material.MatTableModule,
    Material.MatAutocompleteModule,
    Material.MatBottomSheetModule,
    Material.MatBadgeModule,
    Material.MatButtonModule,
    Material.MatButtonToggleModule,
    Material.MatCardModule,
    Material.MatCheckboxModule,
    Material.MatChipsModule,
    Material.MatDatepickerModule,
    Material.MatDialogModule,
    Material.MatDividerModule,
    Material.MatExpansionModule,
    Material.MatGridListModule,
    Material.MatIconModule,
    Material.MatInputModule,
    Material.MatListModule,
    Material.MatMenuModule,
    Material.MatNativeDateModule,
    Material.MatPaginatorModule,
    Material.MatProgressBarModule,
    Material.MatProgressSpinnerModule,
    Material.MatRadioModule,
    Material.MatRippleModule,
    Material.MatSelectModule,
    Material.MatSidenavModule,
    Material.MatSliderModule,
    Material.MatSlideToggleModule,
    Material.MatSnackBarModule,
    Material.MatSortModule,
    Material.MatStepperModule,
    Material.MatTableModule,
    Material.MatTabsModule,
    Material.MatToolbarModule,
    Material.MatTooltipModule,
    Material.MatTreeModule,
    Material.MatFormFieldModule,
    Material.MatInputModule
  ]
})
export class MaterialModule { }
